name: Node.js CI

on:
#   push:
#     branches: [ sidekick ]
  pull_request:
    branches: [ sidekick ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        # !!! Change '16.x' to '12.x'? ???
        node-version: '16.x'
    - run: npm install
    - run: npm test